spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_controller?serverTimezone=UTC
    username: root
    password: crW9r5est
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
server:
  port: 8080
shiro:
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: true
  unauthorizedUrl: "/unauthorizedurl"
  web:
    enabled: true
  successUrl: "/success"
  loginUrl: "/doLogin"
springfox:
  6e082e49-58be-4e18-82cb-d5bcfb9316186e082e49-58be-4e18-82cb-d5bcfb931618
documentation:
    swagger-ui:
      enabled: true6e082e49-58be-4e18-82cb-d5bcfb931618

file:
  upload-dir=./uploads/

